name: build

on:
  push:
    branches:
      - main

jobs:
  R-CMD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: '3.6.1'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GH_PAT_RFASST}}
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2-branch
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Brew and macOS config
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config \
            imagemagick@6 \
            gdal

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")"
